"""Create JobCat model

Revision ID: 2f5cc9945859
Revises: a09ef600d832
Create Date: 2025-05-02 18:47:14.514020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f5cc9945859'
down_revision: Union[str, None] = 'a09ef600d832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_jobs_id', table_name='jobs')
    # op.drop_table('jobs')
    # op.drop_index('user_id', table_name='passResetTokens')
    # op.drop_table('passResetTokens')
    # op.drop_index('user_id', table_name='students')
    # op.drop_table('students')
    # op.drop_index('ix_applications_id', table_name='applications')
    # op.drop_index('job_id', table_name='applications')
    # op.drop_table('applications')
    # op.drop_index('ix_admins_id', table_name='admins')
    # op.drop_index('user_id', table_name='admins')
    # op.drop_table('admins')
    # op.drop_index('user_id', table_name='vTokens')
    # op.drop_table('vTokens')
    # op.drop_index('user_id', table_name='staff')
    # op.drop_table('staff')
    # op.drop_index('ix_users_emailAddy', table_name='users')
    # op.drop_index('ix_users_firstname', table_name='users')
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_index('ix_users_lastname', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('middlename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('emailAddy', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('isVerifiedEmail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_lastname', 'users', ['lastname'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=False)
    op.create_index('ix_users_emailAddy', 'users', ['emailAddy'], unique=True)
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('is_Active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staff_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'staff', ['user_id'], unique=True)
    op.create_table('vTokens',
    sa.Column('emailVerificationToken', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vTokens_ibfk_1'),
    sa.PrimaryKeyConstraint('emailVerificationToken'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'vTokens', ['user_id'], unique=True)
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('is_Active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admins_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'admins', ['user_id'], unique=True)
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('narration', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('doc_1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('doc_2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('doc_3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='applications_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='applications_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('job_id', 'applications', ['job_id'], unique=True)
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('programme', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_Active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_UG', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='students_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'students', ['user_id'], unique=True)
    op.create_table('passResetTokens',
    sa.Column('pToken', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='passResetTokens_ibfk_1'),
    sa.PrimaryKeyConstraint('pToken'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'passResetTokens', ['user_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dateTimeCreated', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('listed_price', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='jobs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###
