"""Update job and jobCat tables 

Revision ID: d0b84475dafc
Revises: 0cd6133d4f3c
Create Date: 2025-05-02 19:34:08.734089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b84475dafc'
down_revision: Union[str, None] = '0cd6133d4f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_category_id', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'jobCategory', ['job_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'deleted')
    op.drop_column('jobs', 'job_category_id')
    # ### end Alembic commands ###
