name: Deploy to aaPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y sshpass

    - name: Deploy via SSH
      run: |
        # Use sshpass with the password from GitHub Secrets for password-based SSH login
        sshpass -p "${{ secrets.AAPANEL_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AAPANEL_USER }}@${{ secrets.AAPANEL_HOST }} <<EOF
          cd ${{ secrets.APP_PATH }}
          git pull origin main
          source /var/www/html/jobapi/_venv/bin/activate
          pip install -r requirements.txt
          touch restart.txt
        EOF
