name: Deploy to cPanel (Local Docker Build)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          host: ${{ secrets.CPANEL_HOST }}
          port: ${{ secrets.CPANEL_PORT || '22' }}
          username: ${{ secrets.CPANEL_USERNAME }}
          private-key: ${{ secrets.CPANEL_PRIVATE_KEY }}
          known_hosts: ${{ secrets.CPANEL_KNOWN_HOSTS }} # Optional

      - name: Transfer code to cPanel
        run: |
          rsync -avz -e "ssh -p ${{ secrets.CPANEL_PORT || '22' }}" \
            ./ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:${{ secrets.CPANEL_PROJECT_PATH }}

      - name: Execute Deployment Script (Build and Run Docker)
        run: |
          ssh ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} -p ${{ secrets.CPANEL_PORT || '22' }} "bash ${{ secrets.CPANEL_PROJECT_PATH }}/deploy.sh"

env:
  CPANEL_PROJECT_PATH: "/home/runedu/public_html/job_be" # Define as an environment variable or secret
