

name: Deploy to aaPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        echo "${{ secrets.AAPANEL_SSH_KEY }}" > /var/www/html/.ssh/ssh_user_key
        chmod 600 /var/www/html/.ssh/ssh_user_key
        ssh-keyscan -H ${{ secrets.AAPANEL_HOST }} >> /var/www/html/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.AAPANEL_USER }}@${{ secrets.AAPANEL_HOST }} <<EOF
          cd ${{ secrets.APP_PATH }}
          git pull origin main
          source /var/www/html/jobapi/_venv/bin/activate
          pip install -r requirements.txt
          touch restart.txt  
        EOF
