name: Deploy to aaPanel (Password Authentication Test - UNSAFE)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Check sshpass installation
      run: which sshpass

    - name: Test SSH with Password (UNSAFE)
      run: |
        echo "Attempting basic SSH with password..."
        sshpass -p "${{ secrets.CPANEL_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} -p ${{ secrets.CPANEL_PORT || '22' }} 'echo "Connected via sshpass!"'
