name: Deploy to aaPanel (Password Authentication - UNSAFE)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password (UNSAFE)
      run: |
        sshpass -p "${{ secrets.CPANEL_PRIVATE_KEY }}" ssh -o StrictHostKeyChecking=yes ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} -p ${{ secrets.CPANEL_PORT || '22' }} "bash ${{ secrets.CPANEL_PROJECT_PATH }}/deploy.sh"
